---
########
########
## CI ##
########
########
name: Continuous Integration

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
# Don't need to run on push to master/main
on:
  push:
    branches-ignore:
      - 'main'

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: CI
    # Set the agent to run on
    runs-on: ubuntu-latest
    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3

      ########################
      # Setup Docker build X #
      ########################
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v2

      ##############################
      # Build the docker container #
      ##############################
      - name: Build Docker container
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            BUILD_DATE=${{ env.BUILD_DATE }}
            BUILD_REVISION=${{ github.sha }}
            BUILD_VERSION=${{ github.sha }}
          push: false
      - run: echo "Hello world!" > world.txt   
      # Upload an artifact to GitHub
      - name: Upload Artifact to Github Build Job
        uses: actions/upload-artifact@v2
        with:
          name: world
          path: world.txt
  hello:
    runs-on: ubuntu-latest
    needs: build
    steps:  
      # Download an artifact from GitHub
      - name: Download Artifact from Github Build Job
        uses: actions/download-artifact@v2
        with:
          name: world
      - run: cat world.txt
